name: "Llama-3.1-8B-Instruct-eng-bio-history"

model:
  name: meta-llama/Llama-3.1-8B-Instruct
data:
  language: english
  use_history: true
  use_bio: true

training:
  output_dir: "../../models"
  max_length: 4500
  optim: "paged_adamw_8bit"
