name: "Ministral-8B-Instruct-2410-eng-bio-history"

model:
  name: mistralai/Ministral-8B-Instruct-2410
data:
  language: english
  use_history: true
  use_bio: true

training:
  output_dir: "../../models"
  max_length: 4500
  optim: "paged_adamw_8bit"
