name: "Qwen3-8B-eng-bio-history"

model:
  name: Qwen/Qwen3-8B
data:
  language: english
  use_history: true
  use_bio: true

training:
  output_dir: "../../models"
  max_length: 4500
  optim: "paged_adamw_8bit"
