name: aya-expanse-8b-lux-history

model:
  name: CohereLabs/aya-expanse-8b
data:
  language: luxembourgish
  use_history: true
  use_bio: false

training:
  output_dir: "../../models"
  max_length: 4000
  optim: "paged_adamw_8bit"