name: ministral-8b-lux-history

model:
  name: mistralai/Ministral-8B-Instruct-2410
data:
  language: luxembourgish
  use_history: true
  use_bio: false

training:
  output_dir: "../../models"
  max_length: 4500
  optim: "paged_adamw_8bit"